### ISSUE TITLE
Bravo 5 Pilot not adding attrition from destiny Draw

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#213] opened 2020-11-11 18:46 UTC
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ideatrack$jzsl0f6mzgxk5hwb

**Comment by EchoBaseTrooper** [comment] 2020-11-11 19:47
Duplicate of https://github.com/PlayersCommittee/gemp-swccg-public/issues/188

**Closed** 2020-11-12 13:53 UTC
