### ISSUE TITLE
BUG - Podracing issues (LS starting interrupt and Anakin's Podracer)

### ISSUE THREAD

**Issue by crazyrunnerguy** [PlayersCommittee/gemp-swccg-public#309] opened 2021-02-15 19:50 UTC
Two issues in this game, which both players were podracing.

LINK: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=CRG$6ps41u3guxxu611s

**ISSUE 1**

During the reveal of starting interrupts, LS's starting interrupt failed for an unknown reason (worked fine in second game were DS was not podracing), causing LS to be unable to deploy its Podrace Arena site or an effect.

Game log

corran reveals Starting Interrupt •Start Your Engines!
CRG reveals Starting Interrupt •Podrace Prep
corran initiates playing •Start Your Engines! from Reserve Deck
corran plays •Start Your Engines! as Starting Interrupt to podrace Arena (with a Podracer, opponent may also deploy a Podracer there), Boonta Eve Podrace, and any Effect that deploys for free
corran deploys •Tatooine: Podrace Arena from Reserve Deck
corran deploys •Sebulba's Podracer from Reserve Deck to •Tatooine: Podrace Arena
CRG deploys •Anakin's Podracer from Reserve Deck to •Tatooine: Podrace Arena
corran targets to deploy Boonta Eve Podrace from Reserve Deck on •Tatooine: Podrace Arena
corran deploys Boonta Eve Podrace from Reserve Deck on •Tatooine: Podrace Arena
corran targets to deploy •Kuat Drive Yards (V) from Reserve Deck
corran deploys •Kuat Drive Yards (V) from Reserve Deck
corran puts •Start Your Engines! in Reserve Deck
**CRG initiates playing •Podrace Prep from Reserve Deck
CRG plays •Podrace Prep as Starting Interrupt to podrace Arena (with a Podracer, opponent may also deploy a Podracer there), Boonta Eve Podrace, and any Effect that deploys for free
corran verifies CRG's Reserve Deck
CRG puts •Podrace Prep in Reserve Deck**

**ISSUE 2**

Turn 2, DS Control phase. 

During LS's T1 draw phase, Anakin's Podracer (correctly) triggered to next turn draw 3 and choose 2. However, in-game, it drew 3, I was able to choose 2, but the game only stacked 1 card on the podracer. The game log reflects what should have happened, but the game itself shows what actually occurred. 

corran reveals Starting Interrupt •Start Your Engines!
CRG reveals Starting Interrupt •Podrace Prep
corran initiates playing •Start Your Engines! from Reserve Deck
corran plays •Start Your Engines! as Starting Interrupt to podrace Arena (with a Podracer, opponent may also deploy a Podracer there), Boonta Eve Podrace, and any Effect that deploys for free
corran deploys •Tatooine: Podrace Arena from Reserve Deck
corran deploys •Sebulba's Podracer from Reserve Deck to •Tatooine: Podrace Arena
CRG deploys •Anakin's Podracer from Reserve Deck to •Tatooine: Podrace Arena
corran targets to deploy Boonta Eve Podrace from Reserve Deck on •Tatooine: Podrace Arena
corran deploys Boonta Eve Podrace from Reserve Deck on •Tatooine: Podrace Arena
corran targets to deploy •Kuat Drive Yards (V) from Reserve Deck
corran deploys •Kuat Drive Yards (V) from Reserve Deck
corran puts •Start Your Engines! in Reserve Deck
CRG initiates playing •Podrace Prep from Reserve Deck
CRG plays •Podrace Prep as Starting Interrupt to podrace Arena (with a Podracer, opponent may also deploy a Podracer there), Boonta Eve Podrace, and any Effect that deploys for free
corran verifies CRG's Reserve Deck
CRG puts •Podrace Prep in Reserve Deck

![Screen Shot 2021-02-15 at 1 46 58 PM](https://user-images.githubusercontent.com/74141260/107987965-a2acab00-6f94-11eb-9ac9-43b1f7e71300.png)

Notice how there is only one card stacked on the podracer (no cards were stacked DS 1 because DS used Sebulba's Podracer's gametext).

This issue corrected itself later in the match on several turns.

**Comment by ideatrack** [comment] 2021-02-15 20:06
There is a workaround for this if you don't select the card on the far right first. If you select either the middle or left card, and then want the right one - this works fine.

**Comment by EchoBaseTrooper** [comment] 2021-02-15 22:38
1) Your starting interrupt failed because it said to deploy a Podracer and you didn't have one in your deck any more. When both players are playing podracing, do not start your podracer with their starting interrupt.
2) duplicate of #187

**Closed by EchoBaseTrooper** 2021-02-15 22:38 UTC
