### ISSUE TITLE
Droid Racks not using reduced cost to remove a card while a piloted MTT on table

### ISSUE THREAD

**Issue by cTherion** [PlayersCommittee/gemp-swccg-public#555] opened 2022-05-11 04:21 UTC
Actual behavior: DS player uses 2 force to take a card stacked on droid racks into hand.

Expected behavior: DS player uses 1 force to take a card stacked on droid racks into hand due to having a piloted MTT on table. (TT-6, an MTT with permanent pilot, is located aboard the Blockade Flagship orbiting Tatooine.)

Issue appears on DS turn 5 control phase.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Therion$q7w2wi1pkcgiu3eq

![image](https://user-images.githubusercontent.com/73430336/167768318-64157e63-ceb5-4a87-aee6-b14bc0dce59b.png)

**Comment by EchoBaseTrooper** [comment] 2022-05-11 04:59
This is not a bug. Vehicles in the cargo hold of a starship are considered unpiloted.

AR 9-16 "A starship at a site location (or a starship or vehicle in a
capital starship's "cargo hold") is "landed." Landed
starships and vehicles are considered unpiloted"

**Closed by EchoBaseTrooper** 2022-05-11 04:59 UTC
