### ISSUE TITLE
Rogue 1 unable to deploy to Naboo (Invasion has cancelled the icons)

### ISSUE THREAD

**Issue by Silverglen** [PlayersCommittee/gemp-swccg-public#553] opened 2022-05-03 16:12 UTC
Adam - in this game I wasn't allowed to deploy rogue 1 to Naboo - I see no reason why. I have previously been able to.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Silverglen$tr9xiqn5jlg8a5ot

**Comment by jokerking16** [comment] 2022-07-09 09:53
https://github.com/PlayersCommittee/gemp-swccg-public/issues/499

**Comment by EchoBaseTrooper** [comment] 2023-03-12 00:44
Duplicate of https://github.com/PlayersCommittee/gemp-swccg-public/issues/499

**Closed by EchoBaseTrooper** 2023-03-12 00:44 UTC
Labels: bug, high priority, In Development

**Comment by Silverglen** [comment] 2023-03-12 10:16
Hi AdamDoes this mean we don’t want rogue 1 or tantive deploying to Naboo t1? Or just rogue 1?Thanks Sent from my iPhoneOn 12 Mar 2023, at 00:44, Adam Fletcher ***@***.***> wrote:﻿
Closed #553 as not planned.
