### ISSUE TITLE
Multiple Bugs - Utinni (V) and Magnetic Suction Tube

### ISSUE THREAD

**Issue by fungineer-86** [PlayersCommittee/gemp-swccg-public#626] opened 2022-08-31 02:14 UTC
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
DS Control Turn 11 - DS Used a magnetic suction tube from an un(driven) vehicle. This shouldn't be allowed per Page 9-17 of AR. 
LS Battle Turn 8 - Utinni (V) was played to "Use" DS's magnetic suction tube. Though it doesn't say "your" you shouldn't be allowed to use opponent's device w/o explicitly stating such. 
Multiple - LS was offered the option to play "Utinni (V)" to 'react' to their own force drain. This shouldn't be allowed. 

## **To Reproduce**
Descriptions above should suffice. 

## **Game Replay ID:**
(https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fungineer$0857i9zd5lz4wt7l)

## **Expected behavior**
Expected - Utinni wouldn't light up on own control phase, wouldn't allow you to "Use" opponent's, and DS couldn't use a device while undriven

**Comment by EchoBaseTrooper** [comment] 2022-09-09 20:44
>Multiple - LS was offered the option to play "Utinni (V)" to 'react' to their own force drain. This shouldn't be allowed.

Utinni! (V) was lighting up as a response to your own drain because of Aved Luun. This is not a bug.


The other items were fixed in the last release.

**Closed by EchoBaseTrooper** 2022-09-09 20:44 UTC
Labels: bug
