### ISSUE TITLE
Mace only able to swing saber once

### ISSUE THREAD

**Issue by SWCCGSlade** [PlayersCommittee/gemp-swccg-public#638] opened 2022-10-10 20:52 UTC
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=AndyDavies$tm9t3p2cfusjb35t

Dark side turn 4 - Battle with Maul & Vader against Mace & Qui-gon. Vader swong at Qui which was Deflected, Qui swings at Maul and missed, Maul swings and hits Qui and then dark plays Dark Strike to make him lost. Mace takes first swing at Maul and missed and then i wasnt given the option to swing the saber a second time.
Took another action to see if that would do anything but the saber still didnt light up.

- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **To Reproduce**
3.
4.
5. See error

**Comment by EchoBaseTrooper** [comment] 2022-10-29 19:45
duplicate of #602

**Closed by EchoBaseTrooper** 2022-10-29 19:45 UTC
Labels: bug, needs triage
