### ISSUE TITLE
Bring Him Before Me does not flip when Luke is captured

### ISSUE THREAD

**Issue by PaulMcPherson** [PlayersCommittee/gemp-swccg-public#372] opened 2021-06-03 11:54 UTC
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Darkbow%24v5xq37l83dsjcm38&fbclid=IwAR1hCXh7_FnWFbdBhr8FW3bj6zbTD5R1lriuK3CignMkh0CziImvnPocDeQ

Luke is captured at the end of LS turn 2 but BHBM does not flip. Another user (derek) posted a very similar issue in chat. Could be something to do with Luke Skywalker, The Emperor's Prize perhaps?

**Comment by PaulMcPherson** [comment] 2021-06-03 13:08
Another game where this happened (DS turn 2 deploy): https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=derek$fgtmhinzqojgj804

**Comment by Echotun** [comment] 2021-06-04 15:41
The issue is indeed The Emperor's Prize. Me and my brother was testing this today. Even if its place OOP, the objective still thinks it's there.
Everything works fine if you remove it.

**Comment by Echotun** [comment] 2021-06-04 17:21
Which still means there is a serious bug that needs fixing ofc. I had a different bug in relation with Hidden Base being placed OOP. Maybe last patch broke som OOP interactions?

**Comment by jdipaolo1** [comment] 2021-06-05 12:59
Should be addressed in latest release.

**Closed by jdipaolo1** 2021-06-05 12:59 UTC
Labels: bug, needs triage
