### ISSUE TITLE
Bug: Not able to draw 3 and pick 2 race destiny still in this example

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#271] opened 2021-01-14 00:19 UTC
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ideatrack$6xvo7931p1p6izys

Doesn't sound like opponent was bothered about reporting it, so I am

**Comment by EchoBaseTrooper** [comment] 2021-01-14 00:29
Duplicate of https://github.com/PlayersCommittee/gemp-swccg-public/issues/187

You could add this as a comment on that bug report if you would like.

**Closed by EchoBaseTrooper** 2021-01-14 00:29 UTC
