### ISSUE TITLE
Game Crashed When Baze Lost

### ISSUE THREAD

**Issue by CoffeePassport** [PlayersCommittee/gemp-swccg-public#490] opened 2021-12-26 14:37 UTC
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Last turn of the game, when Baze is made to be lost by Dr. E and he shoots at P-59 the game crashed. I also had Jedi Lev and Ten Men light up at the same time so maybe it was an interaction with one of those.

## **To Reproduce**
1. See above -- looks like it was some interaction with Baze being made to go lost by Dr. E, firing, and then possibly the triggers from Jedi Lev or Ten Men.

## **Game Replay ID:**
[](https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=CoffeePass$m52yjivhh9uu9gg0)

## **Expected behavior**

Baze to go lost and the game not to crash.

### **Desktop (please complete the following information):**
 - Chrome, Windows 11

**Comment by EchoBaseTrooper** [comment] 2021-12-26 17:14
Duplicate of #476 (which is fixed for the next restart)

**Closed by EchoBaseTrooper** 2021-12-26 17:14 UTC
Labels: bug
